### ISSUE TITLE
What should I put in firebase_options.dart?

### ISSUE THREAD

**Issue by Baruch1515** [Fadilix/FlutterLoginRegister#1]

**Comment by Fadilix** [comment]
You should not directely write in the file. The content of this file will appear after integrating firebase to your project. You should check out the documentation about flutterfire for further clarification

**Comment by Baruch1515** [comment]
thanks it worked for me

**Comment by Baruch1515** [comment]
thanks it worked for me

**Comment by Fadilix** [comment]
You're welcome bro
